import { createContext, useContext, useState, ReactNode } from 'react'

export type Language = 'en' | 'ru'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Script Rating AI',
    'nav.home': 'Home',
    'nav.upload': 'Upload Script',
    'nav.scripts': 'Scripts',
    'script.title': 'Script Title',
    'script.upload': 'Upload',
    'script.analyze': 'Analyze Script',
    'script.analyzing': 'Analyzing...',
    'script.rating': 'Rating',
    'script.scenes': 'scenes',
    'script.uploaded': 'Uploaded',
    'script.not_found': 'Script not found',
    'script.failed_load': 'Failed to load script',
    'script.evidence': 'Evidence from Script',
    'script.analysis_scores': 'Content Analysis Scores',
    'script.high_impact_scenes': 'High-Impact Scenes',
    'script.impact': 'Impact',
    'script.not_rated': 'Not rated yet',
    'script.list_title': 'Scripts',
    'script.list_subtitle': 'All uploaded movie scripts and their ratings',
    'script.upload_title': 'Upload Script',
    'script.upload_subtitle': 'Upload a movie script file to analyze and rate',
    'script.file_label': 'Script File',
    'script.file_action': 'Upload a file',
    'script.file_drag': 'or drag and drop',
    'script.file_format': 'TXT files only',
    'script.file_selected': 'Selected',
    'script.uploading': 'Uploading...',
    'script.error_upload': 'Error uploading file. Please try again.',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'whatif.title': 'What-If Rating Simulator',
    'whatif.current_rating': 'Current Rating',
    'whatif.describe_modification': 'Describe your modification',
    'whatif.placeholder': 'Example: remove scene 12-13, replace fight with verbal conflict, remove all profanity...',
    'whatif.quick_examples': 'Quick examples:',
    'whatif.run_simulation': 'Run Simulation',
    'whatif.simulating': 'Simulating...',
    'whatif.rating_comparison': 'Rating Comparison',
    'whatif.original': 'Original',
    'whatif.modified': 'Modified',
    'whatif.rating_improved': '✓ Rating improved!',
    'whatif.rating_increased': '✗ Rating increased',
    'whatif.applied_changes': 'Applied Changes',
    'whatif.explanation': 'Explanation',
    'whatif.original_scores': 'Original Scores',
    'whatif.modified_scores': 'Modified Scores',
    'category.violence': 'Violence',
    'category.gore': 'Gore',
    'category.sexual': 'Sexual',
    'category.profanity': 'Profanity',
    'category.drugs': 'Drugs',
    'category.nudity': 'Nudity',
    'category.child_risk': 'Child Risk',
    'scene.recommendations': 'Recommendations',
    'scene.score_label': 'Score (%)',
    'theme.toggle': 'Toggle theme',
    'theme.dark': 'Dark mode',
    'theme.light': 'Light mode',
    'language.select': 'Language',
    'heatmap.title': 'Scene Heatmap',
    'heatmap.legend': 'Legend:',
    'whatif.suggestions_title': 'Smart Suggestions',
    'whatif.no_suggestions': 'Start typing to see suggestions...',
    'whatif.suggestion_help': 'Click a suggestion to use it',
    'detections.title': 'Line Detection Analysis',
    'detections.analyze': 'Analyze Lines',
    'detections.analyzing': 'Analyzing...',
    'detections.total': 'Total Detections',
    'detections.falsePositives': 'False Positives',
    'detections.corrections': 'User Corrections',
    'detections.categories': 'Categories',
    'detections.all': 'All',
    'detections.showFalsePositives': 'Show false positives',
    'detections.noDetections': 'No detections found. Click "Analyze Lines" to start.',
    'detections.lines': 'Lines',
    'detections.matches': 'matches',
    'detections.markAsFalsePositive': 'Mark as false positive',
    'detections.markAsValid': 'Mark as valid detection',
    'editor.title': 'Smart Script Editor',
    'editor.hideHighlights': 'Hide highlights',
    'editor.showHighlights': 'Show highlights',
    'editor.reset': 'Reset',
    'editor.save': 'Save',
    'editor.saving': 'Saving...',
    'editor.reanalyze': 'Re-analyze',
    'editor.unsavedChanges': 'You have unsaved changes',
    'editor.lines': 'lines',
    'editor.characters': 'characters',
    'editor.issues': 'issues detected',
    'corrections.addCorrection': 'Add Manual Correction',
    'corrections.type': 'Correction Type',
    'corrections.lineStart': 'Line Start',
    'corrections.lineEnd': 'Line End',
    'corrections.category': 'Category',
    'corrections.severity': 'Severity',
    'corrections.low': 'Low',
    'corrections.medium': 'Medium',
    'corrections.high': 'High',
    'corrections.note': 'Note (optional)',
    'corrections.notePlaceholder': 'Add a note about this correction...',
    'corrections.cancel': 'Cancel',
    'corrections.add': 'Add Correction',
    'corrections.adding': 'Adding...',
    'category.sex_act': 'Sexual Content',
  },
  ru: {
    'app.title': 'ИИ Оценки Сценариев',
    'nav.home': 'Главная',
    'nav.upload': 'Загрузить сценарий',
    'nav.scripts': 'Сценарии',
    'script.title': 'Название сценария',
    'script.upload': 'Загрузить',
    'script.analyze': 'Анализировать сценарий',
    'script.analyzing': 'Анализ...',
    'script.rating': 'Рейтинг',
    'script.scenes': 'сцен',
    'script.uploaded': 'Загружено',
    'script.not_found': 'Сценарий не найден',
    'script.failed_load': 'Не удалось загрузить сценарий',
    'script.evidence': 'Доказательства из сценария',
    'script.analysis_scores': 'Оценки анализа контента',
    'script.high_impact_scenes': 'Сцены с высоким влиянием',
    'script.impact': 'Влияние',
    'script.not_rated': 'Ещё не оценено',
    'script.list_title': 'Сценарии',
    'script.list_subtitle': 'Все загруженные киносценарии и их рейтинги',
    'script.upload_title': 'Загрузка сценария',
    'script.upload_subtitle': 'Загрузите файл киносценария для анализа и оценки',
    'script.file_label': 'Файл сценария',
    'script.file_action': 'Выбрать файл',
    'script.file_drag': 'или перетащите сюда',
    'script.file_format': 'Только TXT файлы',
    'script.file_selected': 'Выбрано',
    'script.uploading': 'Загрузка...',
    'script.error_upload': 'Ошибка загрузки файла. Попробуйте снова.',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'whatif.title': 'Симулятор What-If рейтинга',
    'whatif.current_rating': 'Текущий рейтинг',
    'whatif.describe_modification': 'Опишите изменение',
    'whatif.placeholder': 'Пример: убрать сцену 12-13, заменить драку на словесный конфликт, убрать весь мат...',
    'whatif.quick_examples': 'Быстрые примеры:',
    'whatif.run_simulation': 'Запустить симуляцию',
    'whatif.simulating': 'Симуляция...',
    'whatif.rating_comparison': 'Сравнение рейтингов',
    'whatif.original': 'Оригинал',
    'whatif.modified': 'Изменённый',
    'whatif.rating_improved': '✓ Рейтинг улучшен!',
    'whatif.rating_increased': '✗ Рейтинг увеличен',
    'whatif.applied_changes': 'Применённые изменения',
    'whatif.explanation': 'Объяснение',
    'whatif.original_scores': 'Оригинальные оценки',
    'whatif.modified_scores': 'Изменённые оценки',
    'category.violence': 'Насилие',
    'category.gore': 'Жестокость',
    'category.sexual': 'Сексуальное',
    'category.profanity': 'Мат',
    'category.drugs': 'Наркотики',
    'category.nudity': 'Нагота',
    'category.child_risk': 'Детский риск',
    'scene.recommendations': 'Рекомендации',
    'scene.score_label': 'Оценка (%)',
    'theme.toggle': 'Переключить тему',
    'theme.dark': 'Тёмная тема',
    'theme.light': 'Светлая тема',
    'language.select': 'Язык',
    'heatmap.title': 'Тепловая карта сцен',
    'heatmap.legend': 'Легенда:',
    'whatif.suggestions_title': 'Умные подсказки',
    'whatif.no_suggestions': 'Начните вводить, чтобы увидеть подсказки...',
    'whatif.suggestion_help': 'Нажмите на подсказку, чтобы использовать её',
    'detections.title': 'Анализ проблемных строк',
    'detections.analyze': 'Анализировать строки',
    'detections.analyzing': 'Анализ...',
    'detections.total': 'Всего детекций',
    'detections.falsePositives': 'Ложных срабатываний',
    'detections.corrections': 'Исправлений пользователя',
    'detections.categories': 'Категорий',
    'detections.all': 'Все',
    'detections.showFalsePositives': 'Показать ложные срабатывания',
    'detections.noDetections': 'Детекции не найдены. Нажмите "Анализировать строки" чтобы начать.',
    'detections.lines': 'Строки',
    'detections.matches': 'совпадений',
    'detections.markAsFalsePositive': 'Отметить как ложное срабатывание',
    'detections.markAsValid': 'Отметить как валидное',
    'editor.title': 'Умный редактор сценария',
    'editor.hideHighlights': 'Скрыть подсветку',
    'editor.showHighlights': 'Показать подсветку',
    'editor.reset': 'Сбросить',
    'editor.save': 'Сохранить',
    'editor.saving': 'Сохранение...',
    'editor.reanalyze': 'Переанализировать',
    'editor.unsavedChanges': 'У вас есть несохранённые изменения',
    'editor.lines': 'строк',
    'editor.characters': 'символов',
    'editor.issues': 'проблем найдено',
    'corrections.addCorrection': 'Добавить ручное исправление',
    'corrections.type': 'Тип исправления',
    'corrections.lineStart': 'Начальная строка',
    'corrections.lineEnd': 'Конечная строка',
    'corrections.category': 'Категория',
    'corrections.severity': 'Серьёзность',
    'corrections.low': 'Низкая',
    'corrections.medium': 'Средняя',
    'corrections.high': 'Высокая',
    'corrections.note': 'Примечание (необязательно)',
    'corrections.notePlaceholder': 'Добавьте примечание об этом исправлении...',
    'corrections.cancel': 'Отмена',
    'corrections.add': 'Добавить исправление',
    'corrections.adding': 'Добавление...',
    'category.sex_act': 'Сексуальный контент',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language | null
    return saved || (navigator.language.startsWith('ru') ? 'ru' : 'en')
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
